"""
Pydantic Schemas for Module 13 — Specification Generator.
Adheres strictly to:
1. Grounding in verified project data (standards, versions, QCOs, relationships) and tender context.
2. Complete provenance retention for all generated requirements.
3. Explicit categorization:
   - TENDER_DERIVED
   - RECOMMENDED_STANDARD
   - COMPLIANCE_REQUIREMENT
   - CONDITIONAL_RECOMMENDATION
4. Never invent IS numbers, technical limits, test requirements, or statutory mandates.
5. If data cannot establish a parameter, output UNKNOWN / 'Insufficient verified evidence'.
6. PRIMARY is an internal recommendation designation only.
7. confidence_score is an internal decision-support metric.
8. Regeneration and editing support without corrupting original tender evidence.
"""
from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class SpecificationType(str, Enum):
    """Types of procurement specifications generated by Module 13."""
    TECHNICAL_SPECIFICATION = "technical_specification"
    TENDER_CLAUSE = "tender_clause"
    COMPLIANCE_CHECKLIST = "compliance_checklist"
    AUDIT_CORRECTION = "audit_correction"
    CORRECTIVE_CLAUSE = "corrective_clause"


class RequirementOrigin(str, Enum):
    """Categorical origin of specification requirement."""
    TENDER_DERIVED = "TENDER_DERIVED"
    RECOMMENDED_STANDARD = "RECOMMENDED_STANDARD"
    COMPLIANCE_REQUIREMENT = "COMPLIANCE_REQUIREMENT"
    CONDITIONAL_RECOMMENDATION = "CONDITIONAL_RECOMMENDATION"


class RegulatoryStatus(str, Enum):
    """Regulatory certification status strictly from Module 9 Compliance Intelligence."""
    MANDATORY = "MANDATORY"
    VOLUNTARY = "VOLUNTARY"
    CONDITIONAL = "CONDITIONAL"
    UNKNOWN = "UNKNOWN"


class GeneratedRequirementItem(BaseModel):
    """Individual specification item with strict evidence provenance."""
    item_id: str
    origin: RequirementOrigin
    clause_heading: str
    clause_text: str
    standard_id: Optional[str] = None
    standard_number: Optional[str] = None
    title: Optional[str] = None
    role: Optional[str] = None
    role_disclaimer: str = (
        "Role 'PRIMARY' is an internal recommendation designation indicating the primary matching "
        "standard for query requirements. It is not an official BIS classification."
    )
    regulatory_status: RegulatoryStatus = RegulatoryStatus.UNKNOWN
    is_mandatory: bool = False
    confidence_score: float = 1.0
    confidence_disclaimer: str = (
        "Confidence score is an internal decision-support metric, not a probability, "
        "legal certainty, or claimed correctness percentage."
    )
    trust_level: str = "INFERRED"  # KNOWN, INFERRED, UNKNOWN
    evidence_sources: List[Dict[str, Any]] = Field(default_factory=list)
    verification_notes: Optional[str] = None


class TechnicalSpecificationContent(BaseModel):
    """Structured technical procurement specification document."""
    title: str
    scope_of_work: str
    applicable_standards: List[GeneratedRequirementItem] = Field(default_factory=list)
    technical_parameters: List[Dict[str, Any]] = Field(default_factory=list)
    testing_and_acceptance: List[GeneratedRequirementItem] = Field(default_factory=list)
    safety_and_environmental: List[GeneratedRequirementItem] = Field(default_factory=list)
    mandatory_compliance_clauses: List[GeneratedRequirementItem] = Field(default_factory=list)
    full_text: str
    provenance_summary: List[Dict[str, Any]] = Field(default_factory=list)


class TenderClauseContent(BaseModel):
    """Single procurement clause or corrective clause."""
    title: str
    clause_type: str
    clause_text: str
    incorporated_standards: List[str] = Field(default_factory=list)
    mandatory_certification_clause: Optional[str] = None
    evidence_sources: List[Dict[str, Any]] = Field(default_factory=list)


class ComplianceChecklistItem(BaseModel):
    """Actionable verification item for procurement officials and bidders."""
    item_id: str
    standard_number: str
    standard_title: str
    role: str
    origin: RequirementOrigin
    regulatory_status: str
    mandatory_certification: bool
    qco_number: Optional[str] = None
    verification_method: str
    action_required: str
    evidence_records: List[Dict[str, Any]] = Field(default_factory=list)


class AuditCorrectionContent(BaseModel):
    """Corrected procurement clauses rectifying tender audit gaps."""
    tender_id: int
    total_corrections_made: int
    corrected_clauses: List[Dict[str, Any]] = Field(default_factory=list)
    clean_specification_text: str
    audit_reference: Dict[str, Any] = Field(default_factory=dict)


class SpecificationGenerationRequest(BaseModel):
    """Payload to trigger specification generation."""
    tender_id: Optional[int] = None
    analysis_id: Optional[str] = None
    query_text: Optional[str] = None
    generation_type: SpecificationType = SpecificationType.TECHNICAL_SPECIFICATION
    title: Optional[str] = None
    include_allied: bool = True
    include_checklists: bool = True

    @model_validator(mode="before")
    @classmethod
    def normalize_generation_type(cls, data: Any) -> Any:
        if isinstance(data, dict):
            gt = data.get("generation_type")
            if gt:
                gt_str = str(gt).lower().strip()
                if gt_str in ("gfr_compliance_clause", "tender_clause", "clause", "gfr_clause"):
                    data["generation_type"] = SpecificationType.TENDER_CLAUSE
                elif gt_str in ("testing_schedule", "compliance_checklist", "checklist", "inspection_schedule"):
                    data["generation_type"] = SpecificationType.COMPLIANCE_CHECKLIST
                elif gt_str in ("corrective_clause", "audit_correction", "correction"):
                    data["generation_type"] = SpecificationType.CORRECTIVE_CLAUSE
                elif gt_str in ("technical_specification", "spec", "specification", "full_specification"):
                    data["generation_type"] = SpecificationType.TECHNICAL_SPECIFICATION
        return data


class GeneratedSpecificationResponse(BaseModel):
    """Full API response for generated specification."""
    id: int
    tender_id: Optional[int] = None
    analysis_id: Optional[str] = None
    generation_type: str
    specification_type: Optional[str] = None
    title: str
    generated_text: str
    specification_text: Optional[str] = None
    structured_content: Dict[str, Any] = Field(default_factory=dict)
    provenance_records: List[Dict[str, Any]] = Field(default_factory=list)
    is_edited: bool = False
    version: int = 1
    created_at: Optional[Any] = None
    updated_at: Optional[Any] = None
    disclaimer: str = (
        "System generated specifications are decision-support aids grounded strictly in supplied "
        "BIS records and tender text. They do not constitute official statutory drafting or legal BIS certification."
    )

    @model_validator(mode="after")
    def sync_aliases(self) -> "GeneratedSpecificationResponse":
        if not self.specification_text:
            self.specification_text = self.generated_text
        if not self.specification_type:
            self.specification_type = self.generation_type
        return self


class SpecificationUpdateRequest(BaseModel):
    """Payload to edit or update a generated specification."""
    title: Optional[str] = None
    generated_text: Optional[str] = None
    specification_text: Optional[str] = None
    structured_content: Optional[Dict[str, Any]] = None

    @model_validator(mode="before")
    @classmethod
    def populate_generated_text(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if not data.get("generated_text") and data.get("specification_text"):
                data["generated_text"] = data["specification_text"]
        return data
